Repository maximumJavascript/firebase-study, pull requests merged in 2023-03, with the labels that each got.

#18 Fix create post + fix author
  package-lock.json
  src/App.js
  src/comments/CommentsList/CommentsList.js
  src/comments/PostComments/PostComments.js
  src/home/PostItem/Author/Author.js
  src/home/PostItem/PostItem.js
  src/home/PostItem/Views/Vews.js
  src/home/home.js
  src/posts/createPost.js
  src/sandbox/dropdown/option.js
Labels: bug

#17 Rating
  src/assets/icons/StarIcon.js
  src/assets/icons/SvgEmptyStar.js
  src/auth/auth.service.js
  src/comments/Comment/Comment.js
  src/comments/CommentsList/commentsList.service.js
  src/home/PostItem/PostItem.js
  src/home/PostItem/Raiting/Raiting.js
  src/home/PostItem/Raiting/index.js
  src/home/PostItem/Rating/Rating.js
  src/home/PostItem/Rating/Rating.module.css
  src/home/PostItem/Rating/Star/Star.js
  src/home/PostItem/Rating/Star/Star.module.css
  src/home/PostItem/Rating/Star/index.js
  src/home/PostItem/Rating/index.js
  src/home/PostItem/Rating/rating.service.js
  src/home/PostItem/Views/Views.module.css
  src/home/home.js
  src/sandbox/button/index.js
  src/sandbox/dropdown/dropdown.js
  src/sandbox/dropdown/index.js
Labels: enhancement, need review

#25 fix: change homepage
  package.json
Labels: bug, need review

#26 fix: routes
  src/App.js
  src/header/CentrPartOfNavbar/CentrNavbar.js
  src/sandbox/button/index.js
  src/sandbox/dropdown/dropdown.js
  src/sandbox/dropdown/index.js
Labels: bug, need review
